### ISSUE TITLE
Scrollwheel zoom does not work properly with restrictPosition=false

### ISSUE THREAD

**Issue by pontusdacke** [ValentinH/react-easy-crop#482]
**Describe the bug**
Zooming anchors to incorrect point when using restrictPosition=false. 

**To Reproduce**
1. Set Croppers restrictPosition=false.
2. Scroll down on page.
3. Attempt to scroll using mouse wheel. (Scrollbar appears to work correctly)

https://codesandbox.io/s/react-easy-crop-scroll-demo-forked-zvjhlw?file=/src/Crop.js:1923-1927

**Expected behavior**
Image should zoom correctly like when using restrictPosition=true.

**Comment by ValentinH** [comment]
This looks like a bug because it works correctly on this demo: https://codesandbox.io/s/1rmqky233q 🤔

**Comment by pontusdacke** [comment]
I wasn't very clear but yes the the bug appears only when the page is scrolled. If you add some text before the demo you linked, you will get the same issue when scrolling with the mousewheel. Here is a fork of that demo https://codesandbox.io/s/restrictposition-false-demo-forked-wxxxl2

**Comment by pontusdacke** [comment]
I've opened a PR which appears to solve the problem. Please let me know if you see any improvements that can be made.
I've tested the demo page in npm yarn as well as my own recreation of the problem and found no breaks.

**Comment by ValentinH** [comment]
:rocket: Fix was released in [`v5.0.2`](https://github.com/ValentinH/react-easy-crop/releases/tag/v5.0.2) :rocket:

**Comment by Mizan-Rifat** [comment]
i'm using v5.0.2. Still facing Scrollwheel zoom issue when `restrictPosition={false}`

**Comment by ValentinH** [comment]
I think I'll end up deprecating the restrictPosition option. It's causing many issues and I've never understood the usage.
It goes against the original goal of this lib

**Comment by Mizan-Rifat** [comment]
But `restrictPosition={false}` is needed for some cases. Even i think default value should be `false`

**Comment by ValentinH** [comment]
What is your use case?
